### ISSUE TITLE
i have a issue on heroku

### ISSUE THREAD

**Issue by titu3e** [shardeex/GenshinWishBot#3]
Cause exception while process update id=247530636 by bot id=5342163449
UndefinedTableError: relation "players" does not exist
[wish-sim-bot-logs-1650354238870.txt](https://github.com/shardeex/GIWishBot/files/8510933/wish-sim-bot-logs-1650354238870.txt)

**Comment by shardeex** [comment]
simply create table "players" with columns defined in "app/database/players" via any database browser, for example heidisql

my python code doesn't create table on heroku because I don't need it 😀 sorry, i know it is bad

**Comment by shardeex** [comment]
also you can simply use my bot 😭

**Comment by titu3e** [comment]
ok
thanks
